Adding java version for android integration tests

diff --git a/.github/workflows/flutter-drive.yaml b/.github/workflows/flutter-drive.yaml
--- a/.github/workflows/flutter-drive.yaml
+++ b/.github/workflows/flutter-drive.yaml
@@ -28,6 +28,11 @@ jobs:
       - name: Clone Repository
         uses: actions/checkout@v4
 
+      - name: Set Up Java 11
+        uses: actions/setup-java@v3
+        with:
+          java-version: '11'
+
       - name: Set Up Flutter
         uses: subosito/flutter-action@v2
         with:
@@ -128,7 +133,6 @@ jobs:
           os: iOS
           model: "iPhone 14"
           os_version: ">=13.0"
-          wait_for_boot: true
 
 
       - name: Grant permission
@@ -139,5 +143,10 @@ jobs:
 
       - name: "Run Integration Tests"
         timeout-minutes: 50
-        continue-on-error: true
-        run: firebase emulators:exec --token "${{ secrets.FIREBASE_TOKEN }}" "flutter test integration_test --timeout none" --import=./data
+        run: |
+          set -e
+          firebase emulators:exec --token "${{ secrets.FIREBASE_TOKEN }}" "flutter test integration_test --timeout none" --import=./data || {
+            echo "Integration tests failed"
+            flutter logs
+            exit 1
+          }
